[toolchain]
anchor_version = "0.32.1"
# solana_version  = "1.18.0"

[features]
seeds    = false
skip-lint = false

[programs.localnet]
wager = "Dj2Hot5XJLv9S724BRkWohrhUfzLFERBnZJ9da2WBJQK"

[programs.devnet]
wager = "Dj2Hot5XJLv9S724BRkWohrhUfzLFERBnZJ9da2WBJQK"

[registry]
url = "https://api.apr.dev"

[provider]
cluster  = "localnet"
wallet   = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"